version: "3"
services:
  app:
    build:
      args:
        user: diaz
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php80
    container_name: token-app
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/:cached
    networks:
      - tokenTest

  nginx:
    image: nginx:alpine
    container_name: token-nginx
    ports:
      - 8018:80
    volumes:
      - ./:/var/www/html/:cached
      - ./docker-compose/nginx/:/etc/nginx/conf.d/:cached
    networks:
      - tokenTest
  db:
    image: mysql:5.7
    volumes:
      - ./docker-compose/data:/var/lib/mysql:cached
    container_name: token-mysql
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - tokenTest

networks:
  tokenTest:
    driver: bridge
